const SlidesInfo = {
  deck: {
    title: 'JavaScript from the ground up: Session 1',
  },
  slides: [
    {
      title: 'Front-end Technologies Community of Practice',
      shortTitle: 'Welcome',
      contentFile: 'Welcome',
      baseURL: null,
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Setup',
      shortTitle: 'Setup',
      contentFile: 'Setup',
      baseURL: null,
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Overview',
      shortTitle: 'Overview',
      contentFile: 'Overview',
      baseURL: null,
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Bits',
      shortTitle: 'Bits',
      contentFile: 'Bits',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#p_W1gJpe5a7/',
      linkTitle: 'Eloquent JavaScript: Bits',
    },
    {
      title: 'Values',
      shortTitle: 'Values',
      contentFile: 'Values',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_sVZPaxUSy/',
      linkTitle: 'Eloquent JavaScript: Values',
    },
    {
      title: 'Types',
      shortTitle: 'Types',
      contentFile: 'Types',
      baseURL: null,
      detailLink: 'https://developer.mozilla.org/en-US/docs/Glossary/Type',
      linkTitle: 'MDN article: Type',
    },
    {
      title: 'Primitives',
      shortTitle: 'Primitives',
      contentFile: 'Primitives',
      baseURL: '',
      detailLink: 'https://developer.mozilla.org/en-US/docs/Glossary/Primitive',
      linkTitle: 'MDN article: Primitives',
    },
    {
      title: 'Numbers',
      shortTitle: 'Numbers',
      contentFile: 'Numbers',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_flOCH3CuFg',
      linkTitle: 'Eloquent JavaScript: Numbers',
    },
    {
      title: 'Strings',
      shortTitle: 'Strings',
      contentFile: 'Strings',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_OBbEvqxHHH',
      linkTitle: 'Eloquent JavaScript: Strings',
    },
    {
      title: 'Booleans',
      shortTitle: 'Booleans',
      contentFile: 'Booleans',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_cTPxJxlmFR',
      linkTitle: 'Eloquent JavaScript: Booleans',
    },
    {
      title: 'Empty values',
      shortTitle: 'Empty values',
      contentFile: 'EmptyValues',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_FewqJ8K2E+',
      linkTitle: 'Eloquent JavaScript: Empty values',
    },
    {
      title: 'Operators',
      shortTitle: 'Operators',
      contentFile: 'Operators',
      baseURL: null,
      detailLink:
        'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators',
      linkTitle: 'MDN article: Operators',
    },
    {
      title: 'Unary operators',
      shortTitle: 'Unary operators',
      contentFile: 'UnaryOperators',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#h_ygn12/ieo+',
      linkTitle: 'Eloquent JavaScript: Unary operators',
    },
    {
      title: 'Binary operators',
      shortTitle: 'Binary operators',
      contentFile: 'BinaryOperators',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#p_fvxC7oK7dT',
      linkTitle: 'Eloquent JavaScript: Binary operators',
    },
    {
      title: 'Ternary operator',
      shortTitle: 'Ternary operator',
      contentFile: 'TernaryOperator',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: '#p_EWJu4coIAh',
      linkTitle: 'Eloquent JavaScript: Ternary operator',
    },
    {
      title: 'Exercises, part 1',
      shortTitle: 'Exercises, part 1',
      contentFile: 'Part1Exercises',
      baseURL: 'https://eloquentjavascript.net/01_values.html',
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Part 2: Program structure',
      shortTitle: 'Program structure',
      contentFile: 'OverviewPart2',
      baseURL: null,
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Expressions and statements',
      shortTitle: 'Expressions and statements',
      contentFile: 'ExpressionStatements',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#h_5fUOQZwwHx',
      linkTitle: 'Eloquent JavaScript: Expressions and statements',
    },
    {
      title: 'Bindings and state',
      shortTitle: 'Bindings and state',
      contentFile: 'BindingsState',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#h_lnOC+GBEtu',
      linkTitle: 'Eloquent JavaScript: Bindings',
    },
    {
      title: 'Control flow',
      shortTitle: 'Control flow',
      contentFile: 'ControlFlow',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#h_rDxYNPd65Z',
      linkTitle: 'Eloquent JavaScript: Control flow',
    },
    {
      title: 'If/else',
      shortTitle: 'If/else',
      contentFile: 'IfElse',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#h_wpz5oi2dy7',
      linkTitle: 'Eloquent JavaScript: Conditional execution',
    },
    {
      title: 'For loop',
      shortTitle: 'For loop',
      contentFile: 'ForLoop',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#h_oupMC+5FKN',
      linkTitle: 'Eloquent JavaScript: For loops',
    },
    {
      title: 'Functions',
      shortTitle: 'Functions',
      contentFile: 'Functions',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: null,
      linkTitle: null,
    },
    {
      title: 'Exercises, part 2',
      shortTitle: 'Exercises, part 2',
      contentFile: 'Part2Exercises',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: '#i_rebKE3gdjV',
      linkTitle: 'Eloquent JavaScript: FizzBuzz exercise',
    },
    {
      title: 'References',
      shortTitle: 'References',
      contentFile: 'References',
      baseURL: 'https://eloquentjavascript.net/02_program_structure.html',
      detailLink: null,
      linkTitle: null,
    },
  ],
};

export default SlidesInfo;
