const _Part1List = [
  {
    title: 'Part 1 Overview',
    shortTitle: 'Part 1 Overview',
    directory: 'part-1',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: '(Re)Introducing Functions',
    shortTitle: '(Re)Introducing Functions',
    directory: 'part-1',
    contentFile: 'Introduction1',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Functions',
    shortTitle: 'Functions',
    directory: 'part-1',
    contentFile: 'Introduction2',
    baseURL: null,
    detailLink: 'https://developer.mozilla.org/en-US/docs/Glossary/Function',
    linkTitle: 'Mozilla Developer Network - Functions',
  },
  {
    title: 'Defining a Function',
    shortTitle: 'Defining a Function',
    directory: 'part-1',
    contentFile: 'Defining',
    baseURL: null,
    detailLink:
      'https://www.taniarascia.com/understanding-arrow-functions-in-javascript/#defining-functions',
    linkTitle: 'Tania Rascia - Functions',
  },
  {
    title: 'Bindings and Scopes 1 of 2',
    shortTitle: 'Bindings and Scopes 1',
    directory: 'part-1',
    contentFile: 'BindingsAndScope',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Bindings and Scopes 2 of 2',
    shortTitle: 'Bindings and Scopes 2',
    directory: 'part-1',
    contentFile: 'NestedScope',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Functions as Values',
    shortTitle: 'Functions as Values',
    directory: 'part-1',
    contentFile: 'AsValues',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Declaration Notation',
    shortTitle: 'Declaration Notation',
    directory: 'part-1',
    contentFile: 'DeclarationNotation',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Minimum Exercise',
    shortTitle: 'Minimum Exercise',
    directory: 'part-1',
    contentFile: 'Exercises',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part1List;
