const _Part2List = [
  {
    title: 'Part 2 Overview',
    shortTitle: 'Part 2 Overview',
    directory: 'part-2',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: Arrow Functions Basics',
    shortTitle: 'Arrow Functions',
    directory: 'part-2',
    contentFile: 'ArrowFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: Arrow Functions Basics, continued',
    shortTitle: 'Arrow Functions Cont.',
    directory: 'part-2',
    contentFile: 'ArrowFunctions2',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: More about Arrow Functions',
    shortTitle: 'More Arrow Functions',
    directory: 'part-2',
    contentFile: 'MoreArrowFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: When should I not use Arrow Functions?',
    shortTitle: 'Arrow Functions caveats',
    directory: 'part-2',
    contentFile: 'WhenNotArrowFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: The Call Stack',
    shortTitle: 'Call Stack',
    directory: 'part-2',
    contentFile: 'CallStack',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: Optional Arguments',
    shortTitle: 'Optional Arguments',
    directory: 'part-2',
    contentFile: 'OptionalArguments',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 2: Immediately Invoked Function Expressions',
    shortTitle: 'IIFE',
    directory: 'part-2',
    contentFile: 'IIFE',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  // {
  //   title: 'Example ASCII illustration',
  //   shortTitle: 'Example',
  //   directory: 'part-2',
  //   contentFile: 'ExampleASCII',
  //   baseURL: null,
  //   detailLink: null,
  //   linkTitle: null,
  // },
  // {
  //   title: 'Part 2 Exercises',
  //   shortTitle: 'Part 2 Exercises',
  //   directory: 'part-2',
  //   contentFile: 'Exercises',
  //   baseURL: null,
  //   detailLink: null,
  //   linkTitle: null,
  // },
];

export default _Part2List;
