const _Part3List = [
  {
    title: 'Part 3 Overview',
    shortTitle: 'Part 3 Overview',
    directory: 'part-3',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Closure',
    shortTitle: 'Closure',
    directory: 'part-3',
    contentFile: 'Closure',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Naming Functions',
    shortTitle: 'Naming Functions',
    directory: 'part-3',
    contentFile: 'NamingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Growing Functions',
    shortTitle: 'Growing Functions',
    directory: 'part-3',
    contentFile: 'GrowingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Side Effects and Return Values',
    shortTitle: 'Side Effects / Return Values',
    directory: 'part-3',
    contentFile: 'SideEffectsReturnValue',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Pure Functions',
    shortTitle: 'Pure Functions',
    directory: 'part-3',
    contentFile: 'PureFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Part 3 Exercises',
    shortTitle: 'Part 3 Exercises',
    directory: 'part-3',
    contentFile: 'Exercises',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part3List;
