const _Part3List = [
  {
    title: 'Part 3 Overview',
    shortTitle: 'Part 3 Overview',
    directory: 'part-3',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Closure',
    shortTitle: 'Closure',
    directory: 'part-3',
    contentFile: 'Closure',
    baseURL: null,
    detailLink: 'https://www.manning.com/books/secrets-of-the-javascript-ninja',
    linkTitle: 'Secrets of the JavaScript Ninja',
  },
  {
    title: 'Recursion',
    shortTitle: 'Recursion',
    directory: 'part-3',
    contentFile: 'Recursion',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Side Effects and Return Values',
    shortTitle: 'Side Effects / Return Values',
    directory: 'part-3',
    contentFile: 'SideEffectsReturnValue',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Pure Functions',
    shortTitle: 'Pure Functions',
    directory: 'part-3',
    contentFile: 'PureFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Growing Functions',
    shortTitle: 'Growing Functions',
    directory: 'part-3',
    contentFile: 'GrowingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Naming Functions',
    shortTitle: 'Naming Functions',
    directory: 'part-3',
    contentFile: 'NamingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },

  {
    title: 'Recursion Exercise',
    shortTitle: 'Exercise: Recursion',
    directory: 'part-3',
    contentFile: 'Exercises',
    baseURL: null,
    detailLink: 'https://eloquentjavascript.net/03_functions.html#i_jxl1p970Fy',
    linkTitle: 'Eloquent JS Recursion Exercise',
  },
];

export default _Part3List;
