const _Part3List = [
  {
    title: 'Wrap-up',
    shortTitle: 'Wrap-up',
    directory: 'part-3',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Side Effects and Return Values',
    shortTitle: 'Side Effects / Return Values',
    directory: 'part-3',
    contentFile: 'SideEffectsReturnValue',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Growing Functions',
    shortTitle: 'Growing Functions',
    directory: 'part-3',
    contentFile: 'GrowingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Naming Functions',
    shortTitle: 'Naming Functions',
    directory: 'part-3',
    contentFile: 'NamingFunctions',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Further reading on advanced function concepts',
    shortTitle: 'Advanced topics',
    directory: 'part-3',
    contentFile: 'AdvancedTopics',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Thank-you!',
    shortTitle: 'Thank-you!',
    directory: 'part-3',
    contentFile: 'Thankyou',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part3List;
