const _Part2List = [
  {
    title: 'Recursion Overview',
    shortTitle: 'Recursion Overview',
    directory: 'part-2-recursion',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack',
    shortTitle: 'Call stack',
    directory: 'part-2-recursion',
    contentFile: 'CallStackIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Working with the call stack',
    shortTitle: 'Call stack, cont.',
    directory: 'part-2-recursion',
    contentFile: 'CallStackWorking',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack example',
    shortTitle: 'Call stack example',
    directory: 'part-2-recursion',
    contentFile: 'CallStackExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Introduction to Recursion',
    shortTitle: 'Recursion',
    directory: 'part-2-recursion',
    contentFile: 'RecursionIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion vs Loops',
    shortTitle: 'Recursion vs Loops',
    directory: 'part-2-recursion',
    contentFile: 'RecursionLoops',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Example',
    shortTitle: 'Recursion Example',
    directory: 'part-2-recursion',
    contentFile: 'RecursionExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'In Practice',
    shortTitle: 'In Practice',
    directory: 'part-2-recursion',
    contentFile: 'RecursionInPractice',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'What to watch for',
    shortTitle: 'What to watch for',
    directory: 'part-2-recursion',
    contentFile: 'RecursionWatchFor',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'In the Wild',
    shortTitle: 'In the Wild',
    directory: 'part-2-recursion',
    contentFile: 'RecursionInTheWild',
    baseURL: 'https://',
    detailLink:
      'stackoverflow.com/questions/65474712/deep-copy-object-with-depth-first-search',
    linkTitle: 'Deep copy object with Depth-First Search',
  },
  {
    title: 'Additional resources for advanced functions',
    shortTitle: 'Resources',
    directory: 'part-2-recursion',
    contentFile: 'Resources',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Exercise',
    shortTitle: 'Recursion Exercise',
    directory: 'part-2-recursion',
    contentFile: 'RecursionExercise',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part2List;
