const _Part2List = [
  {
    title: 'Recursion Overview',
    shortTitle: 'Recursion Overview',
    directory: 'part-2-recursion',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack',
    shortTitle: 'Call stack',
    directory: 'part-2-recursion',
    contentFile: 'CallStackIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack - when you run into trouble',
    shortTitle: 'Call stack trouble',
    directory: 'part-2-recursion',
    contentFile: 'CallStackTrouble',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack example',
    shortTitle: 'Call stack example',
    directory: 'part-2-recursion',
    contentFile: 'CallStackExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion intro',
    shortTitle: 'Recursion',
    directory: 'part-2-recursion',
    contentFile: 'RecursionIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion vs Loops',
    shortTitle: 'Recursion vs Loops',
    directory: 'part-2-recursion',
    contentFile: 'RecursionLoops',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Example',
    shortTitle: 'Recursion Example',
    directory: 'part-2-recursion',
    contentFile: 'RecursionExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Exercise',
    shortTitle: 'Recursion Exercise',
    directory: 'part-2-recursion',
    contentFile: 'Exercises',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part2List;
