const _Part2List = [
  {
    title: 'Recursion Overview',
    shortTitle: 'Recursion Overview',
    directory: 'part-2-recursion',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack',
    shortTitle: 'Call stack',
    directory: 'part-2-recursion',
    contentFile: 'CallStackIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Working with the call stack',
    shortTitle: 'Call stack, cont.',
    directory: 'part-2-recursion',
    contentFile: 'CallStackWorking',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Call stack example',
    shortTitle: 'Call stack example',
    directory: 'part-2-recursion',
    contentFile: 'CallStackExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Intro',
    shortTitle: 'Recursion',
    directory: 'part-2-recursion',
    contentFile: 'RecursionIntro',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion vs Loops',
    shortTitle: 'Recursion vs Loops',
    directory: 'part-2-recursion',
    contentFile: 'RecursionLoops',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Example',
    shortTitle: 'Recursion Example',
    directory: 'part-2-recursion',
    contentFile: 'RecursionExample',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Recursion Exercise',
    shortTitle: 'Recursion Exercise',
    directory: 'part-2-recursion',
    contentFile: 'RecursionExercise',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part2List;
