const _Part1List = [
  {
    title: 'Closure Overview',
    shortTitle: 'Closure Overview',
    directory: 'part-1-closure',
    contentFile: 'Overview',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Bindings and Scopes 1 of 2',
    shortTitle: 'Bindings and Scopes 1',
    directory: 'part-1-closure',
    contentFile: 'BindingsAndScope',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Bindings and Scopes 2 of 2',
    shortTitle: 'Bindings and Scopes 2',
    directory: 'part-1-closure',
    contentFile: 'NestedScope',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Closures',
    shortTitle: 'Closures',
    directory: 'part-1-closure',
    contentFile: 'Closure-1',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Closure example',
    shortTitle: 'Closure example',
    directory: 'part-1-closure',
    contentFile: 'Closure-2',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
  {
    title: 'Closures in practice',
    shortTitle: 'Closure in practice',
    directory: 'part-1-closure',
    contentFile: 'Closure-3',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },

  {
    title: 'Closure Exercise',
    shortTitle: 'Closure Exercise',
    directory: 'part-1-closure',
    contentFile: 'Exercises',
    baseURL: null,
    detailLink: null,
    linkTitle: null,
  },
];

export default _Part1List;
